routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('users', 'UserController');

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\UploadedFile;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;

class User extends Model
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'login', 'password_digest', 'firstname', 'lastname', 'birthdate', 'is_active', 'doc_image',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password_digest',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'is_active' => 'boolean',
        'birthdate' => 'date',
    ];

    /**
     * Get the user's full name.
     *
     * @return string
     */
    public function getFullNameAttribute() {
        return "{$this->firstname} {$this->lastname}";
    }

    /**
     * Get the user's full name.
     *
     * @return string
     */
    public function getDocImageUrlAttribute() {
//        return Storage::temporaryUrl(
//            $this->doc_image, now()->addDays(5)
//        );
//        return Storage::url($this->doc_image);
        return "/storage/{$this->doc_image}";
    }

    /**
     * Set the user's password.
     *
     * @param  string $value
     * @return void
     */
    public function setPasswordDigestAttribute($value)
    {
        $this->attributes['password_digest'] = Hash::make($value);
    }

    /**
     * Set the user's doc image.
     *
     * @param  UploadedFile $value
     * @return void
     */
    public function setDocImageAttribute($value)
    {
        if (!is_string($value)) {
            $name = time() . $value->getClientOriginalName();
            $filePath = 'images/' . $name;
            Storage::disk('s3')->put($filePath, file_get_contents($value));
            $this->attributes['doc_image'] = $filePath;
        } else {
            $this->attributes['doc_image'] = $value;
        }
    }

    /**
     * Deletes user
     *
     * @return void
     */
    public function softDelete()
    {
        $this->is_active = false;
        $this->save();
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all()->where('is_active', true);
        return view('users.index', ['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $user = new User($request->all());
        return view('users.create', ['user' => $user]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        echo $request->input('is_active');
        $validatedData = $request->validate([
            'login' => 'required|unique:users|max:255|min:3',
            'password_digest' => 'required|max:255|min:3',
            'firstname' => 'required|max:255|min:3',
            'lastname' => 'required|max:255|min:3',
            'birthdate' => 'required|max:255|min:3',
            'is_active' => 'nullable',
            'doc_image' => 'required|image',
        ]);

        if ($validatedData) {
            $file = $request->file('doc_image');

            $user = new User($validatedData);
            $user->is_active = boolval(isset($validatedData['is_active']) ? $validatedData['is_active'] : false);
            $user->doc_image = $file;

            $user->save();
            return redirect(route('users.show', [$user->id]));
        } else {
            $user = new User($request->all());
            return view('users.create', ['user' => $user]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('users.show', ['user' => $user]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Request $request
     * @param \App\User $user
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, User $user)
    {
        $user->fill($request->all());
        return view('users.edit', ['user' => $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $validatedData = $request->validate([
            'login' => "required|unique:users,login,{$user->id}|max:255|min:3",
            'password_digest' => 'nullable|max:255|min:3',
            'firstname' => 'required|max:255|min:3',
            'lastname' => 'required|max:255|min:3',
            'birthdate' => 'required|max:255|min:3',
            'is_active' => 'nullable',
            'doc_image' => 'nullable|image',
        ]);

        if ($validatedData) {
            $file = $request->file('doc_image');

            $user->fill($validatedData);
            $user->is_active = boolval(isset($validatedData['is_active']) ? $validatedData['is_active'] : false);
            if ($file) {
                $user->doc_image = $file;
            }

            $user->save();
            return redirect(route('users.show', [$user->id]));
        } else {
            $user = new User($request->all());
            return view('users.create', ['user' => $user]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->softDelete();
        return redirect(route('users.index'));
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Nunito', sans-serif;
                font-weight: 200;
                height: 100vh;
                margin: 0;
            }

            .text-left {
                text-align: left;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 13px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            <div class="top-right links">
                <a href="/">Главная</a>
                <a href="{{ route('users.index', null, false) }}">Пользователи</a>
            </div>

            <div class="content">
                @yield('content')
            </div>
        </div>
    </body>
</html>

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')
    <a href="/users">Назад</a>

    <h1>Создать пользователя</h1>

    <div class="text-left">

        @if ($errors->any())
            <div style="color: indianred;">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        {!! Form::open(['route' => ['users.store'], 'files' => true, 'method' => 'post']) !!}
        {!! Form::token(); !!}

            @include('users.form')

        {!! Form::close() !!}
    </div>

@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <a href="{{ route('users.show', [$user->id]) }}">Назад</a>

    <h1>Изменить пользователя {{ $user->full_name }}</h1>
    <h1></h1>
    <div class="text-left">

        @if ($errors->any())
            <div style="color: indianred;">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        {!! Form::open(['route' => ['users.update', $user->id], 'files' => true, 'method' => 'patch']) !!}
        {!! Form::token(); !!}

            @include('users.form')

        {!! Form::close() !!}
    </div>

@endsection

resources/views/users/form.blade.php
<p class="form-group">
    {!! Form::label('login', 'Логин') !!}<br>
    {!! Form::text('login', $user->login, ['class' => 'form-control']) !!}
</p>
<p class="form-group">
    {!! Form::label('password_digest', 'Пароль') !!}<br>
    {!! Form::password('password_digest', ['class' => 'form-control']) !!}
</p>
<p class="form-group">
    {!! Form::label('firstname', 'Имя') !!}<br>
    {!! Form::text('firstname', $user->firstname, ['class' => 'form-control']) !!}
</p>
<p class="form-group">
    {!! Form::label('lastname', 'Фамилия') !!}<br>
    {!! Form::text('lastname', $user->lastname, ['class' => 'form-control']) !!}
</p>
<p class="form-group">
    {!! Form::label('birthdate', 'Дата рождения') !!}<br>
    {!! Form::date('birthdate', $user->birthdate, ['class' => 'form-control']) !!}
</p>
<p class="form-group">
    {!! Form::label('is_active', 'Активный?') !!}<br>
    {!! Form::checkbox('is_active', 'is_active', $user->is_active) !!}
</p>
<p class="form-group">
    <div>Текущее изображение: {{ $user->doc_image }}</div>
    {!! Form::label('doc_image', 'Новое:') !!}</br>
    {!! Form::file('doc_image', null, ['class' => 'form-control']) !!}
</p>
<p>
{!! Form::submit('Сохранить', ['class' => 'btn btn-info']) !!}
</p>

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
    <h1>Пользователи</h1>

    <a href="{{ route('users.create') }}">Добавить пользователя</a>

    @foreach ($users as $user)
        <h3><a href="{{ route('users.show', [$user->id]) }}">{{ $user->full_name }}</a></h3>
        <p>{{ $user->login }}</p>
    @endforeach
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('content')
    <a href="{{ route('users.index') }}">Назад</a>

    <h1>{{ $user->full_name }}</h1>

    <ul class="text-left">
        <li>Логин: {{ $user->login }}</li>
        <li>Пароль: {{ $user->password_digest }}</li>
        <li>Дата рождения: {{ $user->birthdate }}</li>
        <li>Активен?: {{ $user->is_active ? 'Да' : 'Нет' }}</li>
        <li>
            <div>
                Изображение документа:
            </div>
            <div>
                <img src="{{ $user->doc_image_url }}" alt="" style="max-width: 300%; max-height: 200px;">
            </div>
        </li>
    </ul>

    <a href="{{ route('users.edit', [$user->id]) }}">Изменить</a>

    {!! Form::open(['route' => ['users.destroy', $user->id], 'method' => 'delete']) !!}
        {!! Form::button('Удалить', ['type' => 'submit', 'onclick' => "return confirm('Вы уверены?')"]) !!}
    {!! Form::close() !!}
@endsection